financeTracker/debts/forms.py
from flask_wtf import FlaskForm
from wtforms.fields.simple import SubmitField
from wtforms.validators import DataRequired
from wtforms.fields.core import IntegerField, StringField


class DebtForm(FlaskForm):
    debtName = StringField('Debt Name', validators=[DataRequired()])
    amount = IntegerField('Debt Amount', validators=[DataRequired()])
    submit = SubmitField('Add Debt')


class UpdateDebtForm(FlaskForm):
    debtName = StringField('Debt Name', validators=[DataRequired()])
    amount = IntegerField('Debt Amount', validators=[DataRequired()])
    submit = SubmitField('Update Debt')

financeTracker/debts/routes.py
from flask import render_template, Blueprint, redirect, url_for, request
from financeTracker.models import Debt
from financeTracker.debts.forms import DebtForm, UpdateDebtForm
from financeTracker import db

debts = Blueprint('debts', __name__)


@debts.route('/debts')
def debt():
    Debts = Debt.query.all()
    totalDebt = 0
    for debt in Debts:
        totalDebt += debt.amount
    totalDebt = round(totalDebt, 2)
    return render_template('debts/debts.html', Debts=Debts, total=totalDebt)


@debts.route('/debts/new', methods=['GET', 'POST'])
def new_debt():
    form = DebtForm()
    if form.validate_on_submit():
        newDebt = Debt(name=form.debtName.data, amount=form.amount.data)
        db.session.add(newDebt)
        db.session.commit()
        return redirect(url_for('debts.debt'))
    return render_template('/debts/new_debt.html', form=form)


@debts.route('/debts/<int:debt_id>/info', methods=['GET'])
def debt_info(debt_id):
    debt = Debt.query.get_or_404(debt_id)
    return render_template('debts/debt_info.html', debt=debt)


@debts.route('/debts/<int:debt_id>/update', methods=['GET', 'POST'])
def update_debt(debt_id):
    form = UpdateDebtForm()
    debt = Debt.query.get_or_404(debt_id)
    if form.validate_on_submit():
        debt.name = form.debtName.data
        debt.amount = form.amount.data
        db.session.commit()
        return redirect(url_for('debts.debt_info', debt_id=debt.id))
    elif request.method == 'GET':
        form.debtName.data = debt.name
        form.amount.data = debt.amount

    return render_template('debts/update_debt.html', debt=debt, form=form)


@debts.route('/debts/<int:debt_id>/delete', methods=['POST'])
def delete_debt(debt_id):
    debt = Debt.query.get_or_404(debt_id)
    db.session.delete(debt)
    db.session.commit()
    return redirect(url_for('debts.debt'))

financeTracker/templates/debts/debt_info.html
{% extends "base.html" %}

{% block content %}

<div class='content'>
    <main role="main" class="container">
        <div class="row">
            <div class="col-sm-12">
                <article class="media content-section">
                    <div class="media-body">
                        <h2>{{ debt.name }} - {{ debt.amount }}</h2>
                    </div>
                    <div>
                        <a class='a' href='{{ url_for("debts.update_debt", debt_id=debt.id) }}'><button
                                class='btn btn-secondary'>Update</button></a>
                        <button type='button' class='btn btn-dark' data-toggle="modal"
                            data-target="#deleteModal">Delete</button>
                    </div>
                </article>
            </div>
        </div>
    </main>
</div>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Debt - {{ debt.name }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this asset?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('debts.delete_debt', debt_id=debt.id) }}" method='POST'>
                    <input type='submit' class='btn btn-danger' value='Delete'>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}

financeTracker/templates/debts/debts.html
{% extends "base.html" %}

{% block content %}
<div class='table-container'>
    <a class='a btn-group' href='{{ url_for("debts.new_debt") }}'><button id='manualRowBtn' type="button"
            class="btn btn-secondary" title='Add Debt'><i class="fa fa-plus"></i></button></a>
    <table class="table table-hover table-dark">
        <thead>
            <tr>
                <th scope="col">Debt</th>
                <th scope="col">Amount</th>
            </tr>
        </thead>
        <tbody id='debtRows'>
            <div>
                {% for debt in Debts %}
                <tr>
                    <td>{{ debt.name }}</td>
                    <td id='value'>${{ "{:,}".format(debt.amount) }}</td>
                    <td class='center'><a href="{{ url_for('debts.debt_info', debt_id=debt.id) }}"><i
                                class="fas fa-ellipsis-v" title='Edit/More Info'></i></a></td>
                </tr>
                {% endfor %}
            </div>
        </tbody>
        <tr>
            <td>Total Debt</td>
            <td id='total'>${{ "{:,}".format(total) }}</td>
        </tr>

    </table>
</div>






<script type="text/javascript" src="{{url_for('static', filename='js/debts.js')}}"></script>
{% endblock %}

financeTracker/templates/debts/new_debt.html
{% extends "base.html" %}

{% block content %}
<div class='content-section col-md-6 center'>
    <form method='POST'>
        {{ form.hidden_tag() }}
        <fieldset class='form-group'>
            <legend class='center-text'>New Debt</legend>
            <div class='form-group'>
                {{ form.debtName.label(class='form-control-label') }}
                {{ form.debtName(class='form-control form-control-lg') }}
            </div>
            <div class='form-group'>
                {{ form.amount.label(class='form-control-label') }}
                {{ form.amount(class='form-control form-control-lg') }}
            </div>
            <div class='form-group center-text'>
                {{ form.submit(class='btn btn-outline-secondary') }}
            </div>
        </fieldset>
    </form>
</div>






{% endblock %}

financeTracker/templates/debts/update_debt.html
{% extends "base.html" %}

{% block content %}
<div class='content-section col-md-6 center'>
    <form method='POST'>
        {{ form.hidden_tag() }}
        <fieldset class='form-group'>
            <legend class='center-text'>Update Debt</legend>
            <div class='form-group'>
                {{ form.debtName.label(class='form-control-label') }}
                {{ form.debtName(class='form-control form-control-lg') }}
            </div>
            <div class='form-group'>
                {{ form.amount.label(class='form-control-label') }}
                {{ form.amount(class='form-control form-control-lg') }}
            </div>
            <div class='form-group center-text'>
                {{ form.submit(class='btn btn-outline-secondary') }}
            </div>
        </fieldset>
    </form>
</div>






{% endblock %}