financeTracker/spending/forms.py
from flask_wtf import FlaskForm
from flask_wtf.recaptcha import validators
from wtforms import StringField, SubmitField
from wtforms.fields.core import FloatField
from wtforms.validators import DataRequired


class SpendForm(FlaskForm):
    spendName = StringField('Spend Name', validators=[DataRequired()])
    amount = FloatField('Amount', validators=[DataRequired()])
    submit = SubmitField('Add Spend')


class UpdateSpendForm(FlaskForm):
    spendName = StringField('Spend Name', validators=[DataRequired()])
    amount = FloatField('Amount', validators=[DataRequired()])
    submit = SubmitField('Update Spend')

financeTracker/assets/routes.py
from flask import render_template, Blueprint, redirect, url_for, request
from financeTracker.models import Asset
from financeTracker.assets.forms import AssetForm, UpdateAssetForm
from financeTracker import db
from polygon import RESTClient
import datetime
import os


assets = Blueprint('assets', __name__)


@assets.route('/assets')
def asset():
    Assets = Asset.query.all()
    total = 0
    for asset in Assets:
        total += asset.value
    total = round(total, 2)
    return render_template('assets/assets.html', Assets=Assets, total=total)


@assets.route('/assets/new', methods=['GET', 'POST'])
def new_asset():
    form = AssetForm()
    if form.validate_on_submit():
        newAsset = Asset(name=form.assetName.data,
                         value=form.value.data, quantity=form.quantity.data)
        db.session.add(newAsset)
        db.session.commit()
        return redirect(url_for('assets.asset'))
    return render_template('assets/new_asset.html', form=form, title='New Asset')


@assets.route('/assets/<int:asset_id>/info', methods=['GET', 'POST'])
def asset_info(asset_id):
    asset = Asset.query.get_or_404(asset_id)
    return render_template('assets/asset_info.html', asset=asset)


@assets.route('/assets/<int:asset_id>/delete', methods=['POST'])
def delete_asset(asset_id):
    asset = Asset.query.get_or_404(asset_id)
    db.session.delete(asset)
    db.session.commit()
    return redirect(url_for('assets.asset'))


@assets.route('/assets/<int:asset_id>/update', methods=['GET', 'POST'])
def update_asset(asset_id):
    form = UpdateAssetForm()
    asset = Asset.query.get_or_404(asset_id)
    if form.validate_on_submit():
        asset.name = form.assetName.data
        asset.value = form.value.data
        asset.quantity = form.quantity.data
        db.session.commit()
        return redirect(url_for('assets.asset_info', asset_id=asset.id))
    elif request.method == 'GET':
        form.assetName.data = asset.name
        form.value.data = asset.value
        form.quantity.data = asset.quantity

    return render_template('assets/update_asset.html', asset=asset, form=form)


@assets.route('/assets/new/bitcoin', methods=['GET', 'POST'])
def add_bitcoin():
    form = AssetForm()
    key = os.environ.get('PLAID_KEY')

    with RESTClient(key) as client:
        from_ = 'BTC'
        to = 'USD'
        # Making lookup date to always be day before today
        date = datetime.date.today() - datetime.timedelta(1)
        resp = client.crypto_daily_open_close(
            from_, to, date, unadjusted=False
        )

    btc_price = resp.close
    if form.validate_on_submit():
        newAsset = Asset(name=form.assetName.data,
                         value=form.value.data,
                         quantity=form.quantity.data)
        db.session.add(newAsset)
        db.session.commit()
        return redirect(url_for('assets.asset'))
    return render_template('assets/new_bitcoin.html', form=form, title='New Asset', price=btc_price)

financeTracker/spending/routes.py
from flask import render_template, Blueprint, request, redirect, url_for, jsonify
from financeTracker.models import Spending
from financeTracker.spending.forms import SpendForm, UpdateSpendForm
from financeTracker import db
from plaid.model.transactions_get_request import TransactionsGetRequest
from plaid.model.transactions_get_request_options import TransactionsGetRequestOptions
from plaid.api import plaid_api
import os
import plaid
import datetime

spending = Blueprint('spending', __name__)

access_token = os.environ.get('PLAID_ACCESS_TOKEN')

PLAID_CLIENT_ID = os.environ.get(
    'PLAID_CLIENT_ID')
PLAID_SECRET = os.environ.get('PLAID_SECRET')

configuration = plaid.Configuration(
    host=plaid.Environment.Development,
    api_key={
        'clientId': PLAID_CLIENT_ID,
        'secret': PLAID_SECRET,
    }
)
api_client = plaid.ApiClient(configuration)
client = plaid_api.PlaidApi(api_client)


@spending.route('/spending')
def spend():
    start_date = (datetime.datetime.now() - datetime.timedelta(days=30))
    end_date = datetime.datetime.now()
    Spends = Spending.query.all()
    spendTotal = 0
    for spend in Spends:
        if not start_date <= spend.date <= end_date:
            Spends.pop(spend)
        spendTotal += spend.amount
    spendTotal = round(spendTotal, 2)
    return render_template('spending/spending.html', Spends=Spends, total=spendTotal, length=len(Spends))


@spending.route('/spending/new', methods=['GET', 'POST'])
def new_spend():
    form = SpendForm()
    if form.validate_on_submit():
        newSpend = Spending(name=form.spendName.data, amount=form.amount.data)
        db.session.add(newSpend)
        db.session.commit()
        return redirect(url_for('spending.spend'))
    return render_template('spending/new_spend.html', form=form)


@spending.route('/spending/<int:spend_id>/update', methods=['GET', 'POST'])
def update_spend(spend_id):
    form = UpdateSpendForm()
    spend = Spending.query.get_or_404(spend_id)
    if form.validate_on_submit():
        spend.name = form.spendName.data
        spend.amount = form.amount.data
        db.session.commit()
        return redirect(url_for('spending.spend_info', spend_id=spend.id))
    elif request.method == 'GET':
        form.spendName.data = spend.name
        form.amount.data = spend.amount
    return render_template('spending/update_spend.html', form=form, spend=spend)


@spending.route('/spending/<int:spend_id>/info')
def spend_info(spend_id):
    spend = Spending.query.get_or_404(spend_id)
    return render_template('spending/spend_info.html', spend=spend)


@spending.route('/spending/<int:spend_id>/delete', methods=['POST'])
def delete_spend(spend_id):
    spend = Spending.query.get_or_404(spend_id)
    db.session.delete(spend)
    db.session.commit()
    return redirect(url_for('spending.spend'))


@spending.route('/plaid/transactions', methods=['GET'])
def get_transactions():
    # Pull transactions for the last 30 days
    start_date = (datetime.datetime.now() - datetime.timedelta(days=30))
    end_date = datetime.datetime.now()
    try:
        options = TransactionsGetRequestOptions()
        request = TransactionsGetRequest(
            access_token=access_token,
            start_date=start_date.date(),
            end_date=end_date.date(),
            options=options
        )
        response = client.transactions_get(request)
        for transaction in response.to_dict()['transactions']:
            name = (transaction['name'])
            amount = (transaction['amount'])
            transaction_id = (transaction['transaction_id'])
            type = ''
            category = transaction['category']
            print(category)
            if 'Shops' in category:
                type = 'Super'
                type = category[1]
            elif 'Food and Drink' in category:
                type = category[1]
            elif 'Community' in category:
                type = category[1]
            else:
                type = category[0]

            spend = Spending.query.filter_by(
                transaction_id=transaction_id).first()

            if not spend and '-' not in str(amount):
                newSpend = Spending(name=name, amount=amount, type=type,
                                    transaction_id=transaction_id)
                db.session.add(newSpend)
                db.session.commit()

        return redirect(url_for('spending.spend'))
    except plaid.ApiException as e:

        return render_template('spending/spending.html')

# temporary spend deletion route


@spending.route('/spending/delete/all', methods=['GET', 'POST'])
def delete_all():
    spends = Spending.query.all()
    for spend in spends:
        db.session.delete(spend)
        db.session.commit()

financeTracker/templates/spending/new_spend.html
{% extends "base.html" %}

{% block content %}
<div class='content-section col-md-6 center'>
    <form method='POST'>
        {{ form.hidden_tag() }}
        <fieldset class='form-group'>
            <legend class='center-text'>New Spend</legend>
            <div class='form-group'>
                {{ form.spendName.label(class='form-control-label') }}
                {{ form.spendName(class='form-control form-control-lg') }}
            </div>
            <div class='form-group'>
                {{ form.amount.label(class='form-control-label') }}
                {{ form.amount(class='form-control form-control-lg') }}
            </div>
            <div class='form-group center-text'>
                {{ form.submit(class='btn btn-outline-secondary') }}
            </div>
        </fieldset>
    </form>
</div>






{% endblock %}

financeTracker/templates/spending/spend_info.html
{% extends "base.html" %}

{% block content %}

<div class='content'>
    <main role="main" class="container">
        <div class="row">
            <div class="col-sm-12">
                <article class="media content-section">
                    <div class="media-body">
                        <h2>{{ spend.name }} - {{ spend.amount }}</h2>
                    </div>
                    <div>
                        <a class='a' href='{{ url_for("spending.update_spend", spend_id=spend.id) }}'><button
                                class='btn btn-secondary'>Update</button></a>
                        <button type='button' class='btn btn-dark' data-toggle="modal"
                            data-target="#deleteModal">Delete</button>
                    </div>
                </article>
            </div>
        </div>
    </main>
</div>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Spend - {{ spend.name }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this spend?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('spending.delete_spend', spend_id=spend.id) }}" method='POST'>
                    <input type='submit' class='btn btn-danger' value='Delete'>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}

financeTracker/templates/spending/spending.html
{% extends "base.html" %}

{% block content %}

<div class='table-container'>
    <p>Total Transactions - {{ length }}</p>
    <p>TimeFrame - 30 Days</p>
    <!-- <a class='a btn-group' href='{{ url_for("spending.new_spend") }}'><button id='manualRowBtn' type="button"
            class="btn btn-secondary" title='Add Spend'><i class="fa fa-plus"></i></button></a> -->
    <button type="button" class="btn btn-secondary btn-group" data-toggle="dropdown" aria-haspopup="true"
        aria-expanded="false">
        <i class="fa fa-plus"></i>
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton center-text">
        <a class="dropdown-item" href="{{ url_for('assets.new_asset') }}">Custom Spend</a>
        <a class="dropdown-item" href="{{ url_for('spending.get_transactions') }}">Connect Bank</a>
    </div>
    <table class="table table-hover table-dark">
        <thead>
            <tr>
                <th scope="col">Spend</th>
                <th scope='col'>Category</th>
                <th scope="col">Amount</th>
            </tr>
        </thead>
        <tbody id='assetRows'>
            <div>
                {% for spend in Spends %}
                <tr>
                    <td>{{ spend.name }}</td>
                    <td>{{ spend.type }}</td>
                    <td id='value'>${{ "{:,}".format(spend.amount) }}</td>
                    <td class='center'><a href="{{ url_for('spending.spend_info', spend_id=spend.id) }}"><i
                                class="fas fa-ellipsis-v" title='Edit/More Info'></i></a></td>
                </tr>
                {% endfor %}
            </div>
        </tbody>
        <tr>
            <td>Total Spent</td>
            <td id='total'>${{ "{:,}".format(total) }}</td>
        </tr>

    </table>
</div>


{% endblock %}

financeTracker/templates/spending/update_spend.html
{% extends "base.html" %}

{% block content %}
<div class='content-section col-md-6 center'>
    <form method='POST'>
        {{ form.hidden_tag() }}
        <fieldset class='form-group'>
            <legend class='center-text'>Update Spend</legend>
            <div class='form-group'>
                {{ form.spendName.label(class='form-control-label') }}
                {{ form.spendName(class='form-control form-control-lg') }}
            </div>
            <div class='form-group'>
                {{ form.amount.label(class='form-control-label') }}
                {{ form.amount(class='form-control form-control-lg') }}
            </div>
            <div class='form-group center-text'>
                {{ form.submit(class='btn btn-outline-secondary') }}
            </div>
        </fieldset>
    </form>
</div>


{% endblock %}