financeTracker/assets/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, FloatField
from wtforms.validators import DataRequired


class AssetForm(FlaskForm):
    assetName = StringField('Asset Name', validators=[DataRequired()])
    value = FloatField('Value', validators=[DataRequired()])
    quantity = FloatField('Quantity', validators=[],
                          description='If Applicable')
    submit = SubmitField('Add Asset')


class UpdateAssetForm(FlaskForm):
    assetName = StringField('Asset Name', validators=[DataRequired()])
    value = FloatField('Value', validators=[DataRequired()])
    quantity = FloatField('Quantity', validators=[])
    submit = SubmitField('Update Asset')

financeTracker/assets/routes.py
from flask import render_template, Blueprint, redirect, url_for, request
from financeTracker.models import Asset
from financeTracker.assets.forms import AssetForm, UpdateAssetForm
from financeTracker import db
from polygon import RESTClient
import datetime
import os


assets = Blueprint('assets', __name__)


@assets.route('/assets')
def asset():
    Assets = Asset.query.all()
    total = 0
    for asset in Assets:
        total += asset.value
    total = round(total, 2)
    return render_template('assets/assets.html', Assets=Assets, total=total)


@assets.route('/assets/new', methods=['GET', 'POST'])
def new_asset():
    form = AssetForm()
    if form.validate_on_submit():
        newAsset = Asset(name=form.assetName.data,
                         value=form.value.data, quantity=form.quantity.data)
        db.session.add(newAsset)
        db.session.commit()
        return redirect(url_for('assets.asset'))
    return render_template('assets/new_asset.html', form=form, title='New Asset')


@assets.route('/assets/<int:asset_id>/info', methods=['GET', 'POST'])
def asset_info(asset_id):
    asset = Asset.query.get_or_404(asset_id)
    return render_template('assets/asset_info.html', asset=asset)


@assets.route('/assets/<int:asset_id>/delete', methods=['POST'])
def delete_asset(asset_id):
    asset = Asset.query.get_or_404(asset_id)
    db.session.delete(asset)
    db.session.commit()
    return redirect(url_for('assets.asset'))


@assets.route('/assets/<int:asset_id>/update', methods=['GET', 'POST'])
def update_asset(asset_id):
    form = UpdateAssetForm()
    asset = Asset.query.get_or_404(asset_id)
    if form.validate_on_submit():
        asset.name = form.assetName.data
        asset.value = form.value.data
        asset.quantity = form.quantity.data
        db.session.commit()
        return redirect(url_for('assets.asset_info', asset_id=asset.id))
    elif request.method == 'GET':
        form.assetName.data = asset.name
        form.value.data = asset.value
        form.quantity.data = asset.quantity

    return render_template('assets/update_asset.html', asset=asset, form=form)


@assets.route('/assets/new/bitcoin', methods=['GET', 'POST'])
def add_bitcoin():
    form = AssetForm()
    key = os.environ.get('PLAID_KEY')

    with RESTClient(key) as client:
        from_ = 'BTC'
        to = 'USD'
        # Making lookup date to always be day before today
        date = datetime.date.today() - datetime.timedelta(1)
        resp = client.crypto_daily_open_close(
            from_, to, date, unadjusted=False
        )

    btc_price = resp.close
    if form.validate_on_submit():
        newAsset = Asset(name=form.assetName.data,
                         value=form.value.data,
                         quantity=form.quantity.data)
        db.session.add(newAsset)
        db.session.commit()
        return redirect(url_for('assets.asset'))
    return render_template('assets/new_bitcoin.html', form=form, title='New Asset', price=btc_price)

financeTracker/plaid/routes.py
from flask import Blueprint, redirect, url_for
from plaid.model.transactions_get_request import TransactionsGetRequest
from plaid.model.transactions_get_request_options import TransactionsGetRequestOptions
from plaid.model.accounts_get_request import AccountsGetRequest
from plaid.api import plaid_api
from flask import Flask
from flask import render_template
from flask import request
from flask import jsonify
from datetime import datetime
from datetime import timedelta
from financeTracker.models import Asset
from financeTracker import db
import plaid
import base64
import os
import datetime
import json
import time
from dotenv import load_dotenv
from werkzeug.wrappers import response
import os
from financeTracker.assets.forms import AssetForm


PLAID_CLIENT_ID = os.environ.get(
    'PLAID_CLIENT_ID')
PLAID_SECRET = os.environ.get('PLAID_SECRET')

configuration = plaid.Configuration(
    host=plaid.Environment.Development,
    api_key={
        'clientId': PLAID_CLIENT_ID,
        'secret': PLAID_SECRET,
    }
)
api_client = plaid.ApiClient(configuration)
client = plaid_api.PlaidApi(api_client)

access_token = os.environ.get('PLAID_ACCESS_TOKEN')
item_id = os.environ.get('PLAID_ACCESS_TOKEN')
print(PLAID_CLIENT_ID)

plaidapi = Blueprint('plaid', __name__)


@plaidapi.route('/plaid/api')
def plaid():
    return 'connected'


@plaidapi.route('/plaid/accounts', methods=['GET', 'POST'])
def get_accounts():
    form = AssetForm()
    try:
        req = AccountsGetRequest(
            access_token=access_token
        )
        accounts_response = client.accounts_get(req)
    except plaid.ApiException as e:
        response = json.loads(e.body)
        return jsonify({'error': {'status_code': e.status, 'display_message':
                        response['error_message'], 'error_code': response['error_code'], 'error_type': response['error_type']}})

    data = accounts_response.to_dict()
    name = data['accounts'][0]['name']
    balance = data['accounts'][0]['balances']['available']

    if request.method == 'POST':
        if Asset.query.filter_by(name=name).all():
            asset = Asset.query.filter_by(name=name).first()
            asset.value = balance
            db.session.commit()
        else:
            asset = Asset(name=name, value=balance)
            db.session.add(asset)
            db.session.commit()
        return redirect(url_for('assets.asset'))

    form.assetName.data = name
    form.value.data = balance
    return render_template('assets/new_asset.html', form=form)


@plaidapi.route('/plaid/transactions', methods=['GET'])
def get_transactions():
    # Pull transactions for the last 30 days
    start_date = (datetime.datetime.now() - timedelta(days=30))
    end_date = datetime.datetime.now()
    try:
        options = TransactionsGetRequestOptions()
        request = TransactionsGetRequest(
            access_token=access_token,
            start_date=start_date.date(),
            end_date=end_date.date(),
            options=options
        )
        response = client.transactions_get(request)
        print(response.to_dict())
        return response.to_dict()
    except plaid.ApiException as e:

        return jsonify(e)

financeTracker/polygon/routes.py
from flask import Blueprint, render_template, url_for
from werkzeug.utils import redirect
from polygon import RESTClient
import datetime

poly = Blueprint('poly', __name__)


def ts_to_datetime(ts) -> str:
    return datetime.datetime.fromtimestamp(ts / 1000.0).strftime('%Y-%m-%d %H:%M')


@poly.route('/poly')
def polygon():
    key = 'fIImjjcMMqWkvysnEa361gqQ8peH5hRr'
    # RESTClient can be used as a context manager to facilitate closing the underlying http session
    # https://requests.readthedocs.io/en/master/user/advanced/#session-objects
    with RESTClient(key) as client:
        from_ = "2021-01-01"
        to = "2021-02-01"
        resp = client.stocks_equities_aggregates(
            "AAPL", 1, "minute", from_, to, unadjusted=False)

        print(f"Minute aggregates for {resp.ticker} between {from_} and {to}.")

        for result in resp.results:
            dt = ts_to_datetime(result["t"])
            print(
                f"{dt}\n\tO: {result['o']}\n\tH: {result['h']}\n\tL: {result['l']}\n\tC: {result['c']} ")
        return redirect(url_for('assets.asset'))


@poly.route('/bitcoin')
def bitcoin():
    key = 'fIImjjcMMqWkvysnEa361gqQ8peH5hRr'

    with RESTClient(key) as client:
        from_ = 'BTC'
        to = 'USD'
        # Making lookup date to always be day before today
        date = datetime.date.today() - datetime.timedelta(1)
        resp = client.crypto_daily_open_close(
            from_, to, date, unadjusted=False
        )

    btc_price = resp.close

    return f'{btc_price}'

financeTracker/templates/assets/asset_info.html
{% extends "base.html" %}

{% block content %}

<div class='content'>
    <main role="main" class="container">
        <div class="row">
            <div class="col-sm-12">
                <article class="media content-section">
                    <div class="media-body">
                        <h2>{{ asset.name }} - {{ asset.value }}</h2>
                    </div>
                    <div>
                        <a class='a' href='{{ url_for("assets.update_asset", asset_id=asset.id) }}'><button
                                class='btn btn-secondary'>Update</button></a>
                        <button type='button' class='btn btn-dark' data-toggle="modal"
                            data-target="#deleteModal">Delete</button>
                    </div>
                </article>
            </div>
        </div>
    </main>
</div>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Asset - {{ asset.name }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this asset?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('assets.delete_asset', asset_id=asset.id) }}" method='POST'>
                    <input type='submit' class='btn btn-danger' value='Delete'>
                </form>
            </div>
        </div>
    </div>
</div>






{% endblock %}

financeTracker/templates/assets/assets.html
{% extends "base.html" %}

{% block content %}

<div class='table-container'>
    <!-- <a class='a btn-group' href='{{ url_for("assets.new_asset") }}'><button id='manualRowBtn' type="button"
            class="btn btn-secondary" title='Add Asset'><i class="fa fa-plus"></i></button></a> -->
    <button type="button" class="btn btn-secondary btn-group" data-toggle="dropdown" aria-haspopup="true"
        aria-expanded="false">
        <i class="fa fa-plus"></i>
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton center-text">
        <a class="dropdown-item" href="{{ url_for('assets.new_asset') }}">Custom Asset</a>
        <a class="dropdown-item" href="{{ url_for('plaid.get_accounts') }}">Bank</a>
        <a class="dropdown-item" href="{{ url_for('poly.polygon') }}">Stock</a>
        <a class="dropdown-item" href="{{ url_for('assets.add_bitcoin') }}">Bitcoin</a>
    </div>
    <table class="table table-hover table-dark">
        <thead>
            <tr>
                <th scope="col">Asset</th>
                <th scope="col">Value</th>
            </tr>
        </thead>
        <tbody id='assetRows'>
            <div>
                {% for asset in Assets %}
                <tr>
                    <td>{{ asset.name }}</td>
                    <td id='value'>${{ "{:,}".format(asset.value) }}</td>
                    <td class='center'><a href="{{ url_for('assets.asset_info', asset_id=asset.id) }}"><i
                                class="fas fa-ellipsis-v" title='Edit/More Info'></i></a></td>
                </tr>
                {% endfor %}
            </div>
        </tbody>
        <tr>
            <td>Total</td>
            <td id='total'>${{ "{:,}".format(total) }}</td>
        </tr>

    </table>
</div>

<script type="text/javascript" src="{{url_for('static', filename='js/assets.js')}}"></script>

{% endblock %}

financeTracker/templates/assets/new_asset.html
{% extends "base.html" %}

{% block content %}
<div class='content-section col-md-6 center'>
    <form method='POST'>
        {{ form.hidden_tag() }}
        <fieldset class='form-group'>
            <legend class='center-text'>New Asset</legend>

            <div class='form-group'>
                {{ form.assetName.label(class='form-control-label') }}
                {{ form.assetName(class='form-control form-control-lg') }}
            </div>
            <div class='form-group'>
                {{ form.value.label(class='form-control-label') }}
                {{ form.value(class='form-control form-control-lg') }}
            </div>
            <div class='form-group center-text'>
                {{ form.submit(class='btn btn-outline-secondary') }}
            </div>
        </fieldset>
    </form>
</div>






{% endblock %}

financeTracker/templates/assets/new_bank.html
{% extends "base.html" %}

{% block content %}
<div class='content-section col-md-6 center'>
    <form method='POST'>
        {{ form.hidden_tag() }}
        <fieldset class='form-group'>
            <legend class='center-text'>New Asset</legend>

            <div class='form-group'>
                {{ form.assetName.label(class='form-control-label') }}
                {{ form.assetName(class='form-control form-control-lg') }}
            </div>
            <div class='form-group'>
                {{ form.value.label(class='form-control-label') }}
                {{ form.value(class='form-control form-control-lg') }}
            </div>
            <div class='form-group center-text'>
                {{ form.submit(class='btn btn-outline-secondary') }}
            </div>
        </fieldset>
    </form>
</div>

{% endblock %}

financeTracker/templates/assets/new_bitcoin.html
{% extends "base.html" %}

{% block content %}
<div class='content-section col-md-6 center'>
    <form method='POST'>
        {{ form.hidden_tag() }}
        <fieldset class='form-group'>
            <legend class='center-text'>Add Bitcoin: Current Price - <h3 class='price'>{{ price }}</h3>
            </legend>

            <div class='form-group'>
                {{ form.assetName.label(class='form-control-label') }}
                {{ form.assetName(class='form-control form-control-lg', placeholder='BTC') }}
            </div>
            <div class='form-group'>
                {{ form.quantity.label(class='form-control-label') }}
                {{ form.quantity(class='form-control form-control-lg quantity') }}
            </div>
            <div class='form-group'>
                {{ form.value.label(class='form-control-label') }}
                {{ form.value(class='form-control form-control-lg value') }}
            </div>
            <div class='form-group center-text'>
                {{ form.submit(class='btn btn-outline-secondary') }}
            </div>
        </fieldset>
    </form>
</div>


<script>
    let quantity = document.querySelector('.quantity');
    let value = document.querySelector('.value')
    let price = document.querySelector('.price')
    console.log(price.innerHTML)
    quantity.addEventListener('keyup', () => {
        btcPrice = parseInt(price.innerHTML);
        value.value = (quantity.value * btcPrice).toFixed(2);
    })
</script>



{% endblock %}

financeTracker/templates/assets/update_asset.html
{% extends "base.html" %}

{% block content %}
<div class='content-section col-md-6 center'>
    <form method='POST'>
        {{ form.hidden_tag() }}
        <fieldset class='form-group'>
            <legend class='center-text'>Update Asset</legend>
            <div class='form-group'>
                {{ form.assetName.label(class='form-control-label') }}
                {{ form.assetName(class='form-control form-control-lg') }}
            </div>
            <div class='form-group'>
                {{ form.value.label(class='form-control-label') }}
                {{ form.value(class='form-control form-control-lg') }}
            </div>
            <div class="btn-group">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Connect
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{{ url_for('plaid.get_accounts') }}">Bank </a>
                    <a class="dropdown-item" href="#">Exchanges</a>
                    <a class="dropdown-item" href="#">Stock</a>
                    <a class="dropdown-item" href="#">Crypto</a>
                </div>
            </div>
            <div class='form-group center-text'>
                {{ form.submit(class='btn btn-outline-secondary') }}
            </div>
        </fieldset>
    </form>
</div>






{% endblock %}